version: "3.7"

services:
  lang:
    container_name: lang
    image: lang
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: streamlit run main.py
    ports:
      - 8501:8501
    volumes:
      - .:/app
    env_file:
      - .env
  postgres:
    image: postgres:15.2-alpine
    container_name: postgres-lang
    restart: always
    environment:
      - POSTGRES_USER=stream
      - POSTGRES_PASSWORD=pass111
      - POSTGRES_DB=streamdb
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

volumes:
  postgres_data: